### ISSUE TITLE
Error: Cannot find module 'caniuse-db/data'

### ISSUE THREAD

**Issue by as535364** [joemccann/dillinger#339]
i got an error when i install on ubuntu 14.04

gulp build --prod

Error: Cannot find module 'caniuse-db/data'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/dillinger/node_modules/gulp-autoprefixer/node_modules/autoprefixer-core/data/browsers.js:58:10)
    at Object.<anonymous> (/var/dillinger/node_modules/gulp-autoprefixer/node_modules/autoprefixer-core/data/browsers.js:64:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/dillinger/node_modules/gulp-autoprefixer/node_modules/autoprefixer-core/lib/autoprefixer.js:48:15)
    at Object.<anonymous> (/var/dillinger/node_modules/gulp-autoprefixer/node_modules/autoprefixer-core/lib/autoprefixer.js:111:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
root@Server:/var/dillinger# Error: Cannot find module 'caniuse-db/data'
Error:: command not found

**Comment by joemccann** [comment]
This should be fixed.
