### ISSUE TITLE
Cannot link Dropbox

### ISSUE THREAD

**Issue by meskobalazs** [joemccann/dillinger#342]
For some reason, the dropbox linking is not working on my local Dillinger. When the authentication returns to the local Dillinger URL, I click on Import from Dropbox, then it fails with "Error: null", and crashes with this in the console:

    SyntaxError: Invalid regular expression: /^\/: \ at end of pattern
      at RegExp (native)
      at RegExp (C:\Users\meb\Documents\GitHub\dillinger\node_modules\markdown-it-math\node_modules\ascii2mathml\node_modules\babel\node_modules\babel-core\node_modules\core-js\modules\es6.regexp.constructor.js:25:76)
      at Object.parseJSON (C:\Users\meb\Documents\GitHub\dillinger\node_modules\dbox\lib\helpers.js:23:27)
      at Request._callback (C:\Users\meb\Documents\GitHub\dillinger\node_modules\dbox\lib\dbox.js:61:60)
      at Request.self.callback (C:\Users\meb\Documents\GitHub\dillinger\node_modules\dbox\node_modules\request\main.js:119:22)
      at Request.<anonymous> (C:\Users\meb\Documents\GitHub\dillinger\node_modules\dbox\node_modules\request\main.js:525:16)
      at Request.emit (events.js:107:17)
      at IncomingMessage.<anonymous> (C:\Users\meb\Documents\GitHub\dillinger\node_modules\dbox\node_modules\request\main.js:484:14)
      at IncomingMessage.emit (events.js:129:20)
      at _stream_readable.js:908:16

Also, I am not sure what should I put in the place of `YOUR_CALLBACK_URL`, it is really not self-evident.

**Comment by joemccann** [comment]
Have a look at the `README.md` in the dropbox plugin folder.
