### ISSUE TITLE
Cannot complete install

### ISSUE THREAD

**Issue by eroji** [joemccann/dillinger#488]
I am attempting to install Dillinger on CentOS7 box and this is the error I'm getting:

```
npm info install phantomjs@1.9.19

> phantomjs@1.9.19 install /root/dillinger/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /root/dillinger/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [================================--------] 79% 0.0s
Received 12854K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { [Error: Command failed: tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
] killed: false, code: 2, signal: null } Error: Command failed: tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
npm info phantomjs@1.9.19 Failed to exec install script
npm info /root/dillinger/node_modules/phantomjs unbuild
npm info preuninstall phantomjs@1.9.19
npm info uninstall phantomjs@1.9.19
npm info postuninstall phantomjs@1.9.19
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by eroji** [comment]
Fixed. Needed bzip2.
