### ISSUE TITLE
cannot find the file app/public/css/app.css after deploying to heroku

### ISSUE THREAD

**Issue by lbsong** [joemccann/dillinger#514]
I deployed dillinger to heroku, and try to access it from browser, but got Application Error. from the logs, it complains the file app/public/css/app.css cannot be found. 

But it works well locally on my computer. 

Any idea?

**Comment by joemccann** [comment]
Are you running `gulp build --prod`?

On Monday, April 4, 2016, lbsong <notifications@github.com> wrote:

> I deployed dillinger to heroku, and try to access it from browser, but got
> Application Error. from the logs, it complains the file
> app/public/css/app.css cannot be found.
>
> But it works well locally on my computer.
>
> Any idea?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joemccann/dillinger/issues/514>
>


-- 
Sent from Joe In Real Life

**Comment by lbsong** [comment]
Thanks Joe! yes, I did run the command "gulp build --prod". here is the steps what I did: 

1. gulp build --prod
2. git push heroku master

The below is the heroku logs. And I found if I moved the line 

`var _format = fs.readFileSync( path.resolve(__dirname, '../../public/css/app.css') ).toString('utf-8');`

to the inside of the function _getFormat. It does not have this error but no style applied either. 

2016-04-04T20:57:54.937819+00:00 app[web.1]: Error: ENOENT: no such file or directory, open '/app/public/css/app.css'
2016-04-04T20:57:54.937820+00:00 app[web.1]:     at Error (native)
2016-04-04T20:57:54.937821+00:00 app[web.1]:     at Object.fs.openSync (fs.js:549:18)
2016-04-04T20:57:54.937821+00:00 app[web.1]:     at Object.fs.readFileSync (fs.js:397:15)
2016-04-04T20:57:54.937822+00:00 app[web.1]:     at Object.<anonymous> (/app/plugins/core/server.js:27:20)
2016-04-04T20:57:54.937823+00:00 app[web.1]:     at Module._compile (module.js:409:26)
2016-04-04T20:57:54.937823+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:416:10)
2016-04-04T20:57:54.937824+00:00 app[web.1]:     at Module.load (module.js:343:32)
2016-04-04T20:57:54.937825+00:00 app[web.1]:     at Function.Module._load (module.js:300:12)
2016-04-04T20:57:54.937825+00:00 app[web.1]:     at Module.require (module.js:353:17)
2016-04-04T20:57:54.937826+00:00 app[web.1]:     at require (internal/module.js:12:17)
2016-04-04T20:57:55.616612+00:00 heroku[web.1]: State changed from starting to crashed
2016-04-04T20:57:55.598962+00:00 heroku[web.1]: Process exited with status 1

**Comment by benjamin-albert** [comment]
@lbsong Can you send us the Gulp output and confirm that it's producing `app.css` in to correct location?

**Comment by lbsong** [comment]
@benjamin-albert Thanks for replying. the output is attached. And I think the file app.css is produced to correct location as I can see the file dillinger\public\css\app.css
[gulp-build-output.txt](https://github.com/joemccann/dillinger/files/249288/gulp-build-output.txt)

**Comment by benjamin-albert** [comment]
According to the stack trace you posted in your [previous comment](https://github.com/joemccann/dillinger/issues/514#issuecomment-205496587) the server is trying to open '/app/public/css/app.css', but you say it's created at `dillinger\public\css\app.css`.

@lbsong Can you confirm that the server is trying to read from the correct location?

**Comment by lbsong** [comment]
@benjamin-albert Thank you Benjamin for help! I finally figured it out. It's because dillinger requires to be built with gulp, but heroku doesn't have gulp in place. I have to update package.json to put the dependicies from devDependencies to dependenicies section. and add "postinstall": "gulp build --prod" into scripts section in package.json.

**Comment by benjamin-albert** [comment]
@lbsong You're welcome :)  Is it possible to send us your `package.json` it can help us prevent issues like this in the future.

**Comment by lbsong** [comment]
of course! Attached. 
[package.json.txt](https://github.com/joemccann/dillinger/files/251060/package.json.txt)
