### ISSUE TITLE
Error during install #phantomjs

### ISSUE THREAD

**Issue by noraj1337** [joemccann/dillinger#538]
Hi, I got an error during the install : 
```
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/dillinger/npm-debug.log
npm ERR! not ok code 0
```

so here is the end of  `/var/www/dillinger/npm-debug.log` : 
```
99170 silly gunzTarPerm extractEntry build/test-prefix.js
99171 silly gunzTarPerm extractEntry build/test-suffix.js
99172 error phantomjs@1.9.20 install: `node install.js`
99172 error Exit status 127
99173 error Failed at the phantomjs@1.9.20 install script.
99173 error This is most likely a problem with the phantomjs package,
99173 error not with npm itself.
99173 error Tell the author that this fails on your system:
99173 error     node install.js
99173 error You can get their info via:
99173 error     npm owner ls phantomjs
99173 error There is likely additional logging output above.
99174 error System Linux 3.16.0-4-amd64
99175 error command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-d"
99176 error cwd /var/www/dillinger
99177 error node -v v0.10.29
```

**Comment by benjamin-albert** [comment]
The `phantomjs` package seems to be a dev dependency.

Are you trying to build for development or production?

Just as the log says it looks like it's an issue with the `phantomjs` package on your platform.

Stay tuned while I check what this package is being used for in the code.
Maybe it's possible to remove this dev dependency and resolve this issue at the same time.

**Comment by benjamin-albert** [comment]
BTW what platform (OS) are you trying to install Dillinger on?

**Comment by shark-oxi** [comment]
I send a mail to the phantomjs owner too.
I want a production build.
I'm trying to install it on Debian 8.

**Comment by benjamin-albert** [comment]
I can confirm that the `phantomjs` module is only needed in development so you can skip installing it by running:

    npm install --production.

But unfortunately `gulp build --prod` (which runs during `npm install --production` and is necasery for deploying) references dome devDependencies.

Stay tuned for a pull request that fixes this issue.

I still think it's worth opening an issue on the [phantomjs issue tracker] (https://github.com/Medium/phantomjs/issues).

**Comment by shark-oxi** [comment]
I didn't see first but in the middle of the code there is a more complete error message : 
```
npm info install phantomjs@1.9.20

> phantomjs@1.9.20 install /var/www/dillinger/node_modules/phantomjs
> node install.js

sh: 1: node: not found
npm info phantomjs@1.9.20 Failed to exec install script
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm info preuninstall phantomjs@1.9.20
npm info uninstall phantomjs@1.9.20
npm info postuninstall phantomjs@1.9.20
npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the phantomjs@1.9.20 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-d"
npm ERR! cwd /var/www/dillinger
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
```

This line `npm WARN This failure might be due to the use of legacy binary "node"` call me out.


and at the end of `/usr/share/doc/nodejs/README.Debian` I can read : 

```
nodejs command
--------------

The upstream name for the Node.js interpreter command is "node".
In Debian the interpreter command has been changed to "nodejs".

This was done to prevent a namespace collision: other commands use
the same name in their upstreams, such as ax25-node from the "node"
package.

Scripts calling Node.js as a shell command must be changed to instead
use the "nodejs" command.
```

Is that the reason ?

**Comment by shark-oxi** [comment]
I opened an [issue ](https://github.com/Medium/phantomjs/issues/545) on the phantomjs issue tracker.

**Comment by shark-oxi** [comment]
So the **first** phantomjs [issue](https://github.com/Medium/phantomjs/issues/545) is solved.
I installed `apt-get install nodejs-legacy` and run `npm i -d` again this time without error.

But now when I do `NODE_ENV=production node app` I get : 
```
$ NODE_ENV=production node app
Dropbox config not found at /var/www/dillinger/plugins/dropbox/dropbox-config.json. Plugin disabled.
Github config not found at /var/www/dillinger/plugins/github/github-config.json. Plugin disabled.
Google Drive config not found at /var/www/dillinger/plugins/googledrive/googledrive-config.json. Plugin disabled.
OneDrive config not found at /var/www/dillinger/plugins/onedrive/onedrive-config.json. Plugin disabled.

/var/www/dillinger/plugins/core/server.js:92
    getPhantomSession().then(phantom => {
                                      ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/dillinger/app.js:23:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```
I don't know if, this time, it comes from phantomjs or the server.js file.

**Comment by joemccann** [comment]
you need Node v4+

**Comment by shark-oxi** [comment]
I rebuilt it with nodejs v4.4.4 and when I try to running I still have an error : 
```bash
$ nodejs --version
v4.4.4
$ NODE_ENV=production node app
Dropbox config not found at /var/www/dillinger/plugins/dropbox/dropbox-config.json. Plugin disabled.
Github config not found at /var/www/dillinger/plugins/github/github-config.json. Plugin disabled.
Google Drive config not found at /var/www/dillinger/plugins/googledrive/googledrive-config.json. Plugin disabled.
OneDrive config not found at /var/www/dillinger/plugins/onedrive/onedrive-config.json. Plugin disabled.
module.js:327
    throw err;
    ^

Error: Cannot find module 'temp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/dillinger/plugins/core/server.js:6:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by benjamin-albert** [comment]
Can you check the `node_modules` directory to see if you can find the `temp` module (directory)?

If you can't find it please try running just: 

    npm install > npm-install.log

If you still don't get the `temp` module, please send us the `npm-install.log` file along with the npm version:

    npm --version

**Comment by shark-oxi** [comment]
When I run `npm i -d > npm-install.log` first time I get these [logs](https://gist.github.com/shark-oxi/ed8af4362f1117d200b8c358dae3d49a).
and second time `npm install > npm-install2.log` I got nothing.
Temp is not present after install.

Npm version : 2.15.1

**Comment by benjamin-albert** [comment]
Can you try to explicitly install the `temp` module:

    npm install temp

If this doesn't work I will ret to reproduce the issue on my machine.

**Comment by shark-oxi** [comment]
Installing `temp` seems to work : 
```
$ sudo npm install temp
temp@0.8.3 node_modules/temp
├── os-tmpdir@1.0.1
└── rimraf@2.2.8
```
but I still can't run `dillinger` : 
```
$ sudo nodejs app
Dropbox config not found at /var/www/dillinger/plugins/dropbox/dropbox-config.json. Plugin disabled.
Github config not found at /var/www/dillinger/plugins/github/github-config.json. Plugin disabled.
Google Drive config not found at /var/www/dillinger/plugins/googledrive/googledrive-config.json. Plugin disabled.
OneDrive config not found at /var/www/dillinger/plugins/onedrive/onedrive-config.json. Plugin disabled.
module.js:327
    throw err;
    ^

Error: Cannot find module 'phantom'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/dillinger/plugins/core/server.js:7:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by benjamin-albert** [comment]
@shark-oxi Can you try deleting the `mode_modules` directory and running `npm install` **(without sudo)**.

I think a bad installation was left behind when you ran `npm i -d` on an older node version.

Please note that `sudo` is only required on some platforms (most notably OS X) when using the `-g` (global) option.

**Comment by shark-oxi** [comment]
When I did that it was clean install from a new cloned folder and I use sudo because it's a root owned folder

**Comment by benjamin-albert** [comment]
@shark-oxi Can you try updating npm to the latest version:

    npm install -g npm

**Comment by shark-oxi** [comment]
```
npm --version
3.9.0
```

and now tried again : 
```
$ sudo npm install temp
os-tmpdir@1.0.1 node_modules/temp/node_modules/os-tmpdir -> node_modules/os-tmpdir
rimraf@2.2.8 node_modules/temp/node_modules/rimraf -> node_modules/rimraf
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN optional Skipping failed optional dependency /markdown-it-math/ascii2mathml/babel/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN optional Skipping failed optional dependency /webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12

$ sudo nodejs app
Dropbox config not found at /var/www/dillinger/plugins/dropbox/dropbox-config.json. Plugin disabled.
Github config not found at /var/www/dillinger/plugins/github/github-config.json. Plugin disabled.
Google Drive config not found at /var/www/dillinger/plugins/googledrive/googledrive-config.json. Plugin disabled.
OneDrive config not found at /var/www/dillinger/plugins/onedrive/onedrive-config.json. Plugin disabled.
module.js:327
    throw err;
    ^

Error: Cannot find module 'phantom'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/dillinger/plugins/core/server.js:7:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

$ sudo npm i phantomjs
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "phsudo" "npm" "i" "phantomjs"
npm ERR! node v4.4.4
npm ERR! npm  v3.9.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/phsudo
npm ERR! 404 
npm ERR! 404  'phsudo' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/dillinger/npm-debug.log
```

So here is the log file : https://gist.github.com/shark-oxi/171f02d765075c923decc93155dc9a9d

**Comment by benjamin-albert** [comment]
I want to try to isolate the problem.

Can you try to install Dillinger on a different machine.

This way we can see if the problem is in this machine or something in your network that prevents those dependencies from being installed.

I have successfully installed (and built from source) Dillinger on multiple machines running on different operating systems.

I don't see any reason that NPM should have a problem installing those dependencies.

**Comment by benjamin-albert** [comment]
This issue has been inactive quite a while so I'm closing it.
