### ISSUE TITLE
Debian Install fails

### ISSUE THREAD

**Issue by wirehack7** [joemccann/dillinger#547]
Using Debian 8:

```
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "-d"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/node/dillinger/npm-debug.log
```

So, Debian is unsupported, maybe write that also in Readme

**Comment by joemccann** [comment]
yes I'm getting the same issue

**Comment by benjamin-albert** [comment]
I believe npm/npm#8707 is the culprit.

Looking at the [npm-shrinkwrap.json blame](https://github.com/joemccann/dillinger/blame/master/npm-shrinkwrap.json) you can see it was recently modified in #542 (which I'm guessing caused this issue).

@wirehack7 Can you try to updating npm by running:

    $ npm install npm -g

**Comment by wirehack7** [comment]
Now I get:

npm info lifecycle fsevents@1.0.12~install: fsevents@1.0.12

```
> fsevents@1.0.12 install /home/node/dillinger/node_modules/markdown-it-math/node_modules/ascii2mathml/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build
```

**Comment by benjamin-albert** [comment]
@wirehack7 Can you try running:

    $ gulp build --prod

It should produce those file from source.

**Comment by wirehack7** [comment]
```bash
 $: gulp build --prod
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/home/node/dillinger/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.getInstalledBinaries (/home/node/dillinger/node_modules/node-sass/lib/extensions.js:74:13)
    at foundBinariesList (/home/node/dillinger/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/node/dillinger/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/node/dillinger/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/home/node/dillinger/node_modules/node-sass/lib/index.js:14:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/node/dillinger/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

I think it's because packages install fails before:

```bash
npm info lifecycle on-finished@2.3.0~install: on-finished@2.3.0
npm info lifecycle on-headers@1.0.1~install: on-headers@1.0.1
npm info lifecycle nan@2.3.3~install: nan@2.3.3
npm info lifecycle fsevents@1.0.12~install: fsevents@1.0.12

> fsevents@1.0.12 install /home/node/dillinger/node_modules/markdown-it-math/node_modules/ascii2mathml/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build
```

```
$: node -v
v4.4.4
$: npm -v
3.9.2
```

**Comment by wirehack7** [comment]
Removed nodejs with npm from system. Installed from nodejs repo.
Now I get this:

```
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.2
npm ERR! code ELIFECYCLE
npm ERR! Dillinger@3.3.0 postinstall: `gulp build --prod`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the Dillinger@3.3.0 postinstall script 'gulp build --prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Dillinger package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build --prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Dillinger
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Dillinger
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/node/dillinger/npm-debug.log
```
npm-debug.log:
```
36068 silly lifecycle Dillinger@3.3.0~postinstall: Args: [ '-c', 'gulp build --prod' ]
36069 silly lifecycle Dillinger@3.3.0~postinstall: Returned: code: 137  signal: null
36070 info lifecycle Dillinger@3.3.0~postinstall: Failed to exec postinstall script
36071 verbose stack Error: Dillinger@3.3.0 postinstall: `gulp build --prod`
36071 verbose stack Exit status 137
36071 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
36071 verbose stack     at emitTwo (events.js:87:13)
36071 verbose stack     at EventEmitter.emit (events.js:172:7)
36071 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
36071 verbose stack     at emitTwo (events.js:87:13)
36071 verbose stack     at ChildProcess.emit (events.js:172:7)
36071 verbose stack     at maybeClose (internal/child_process.js:827:16)
36071 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
36072 verbose pkgid Dillinger@3.3.0
36073 verbose cwd /home/node/dillinger
36074 error Linux 3.16.0-4-amd64
36075 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
36076 error node v4.4.5
36077 error npm  v3.9.2
36078 error code ELIFECYCLE
36079 error Dillinger@3.3.0 postinstall: `gulp build --prod`
36079 error Exit status 137
36080 error Failed at the Dillinger@3.3.0 postinstall script 'gulp build --prod'.
36080 error Make sure you have the latest version of node.js and npm installed.
36080 error If you do, this is most likely a problem with the Dillinger package,
36080 error not with npm itself.
36080 error Tell the author that this fails on your system:
36080 error     gulp build --prod
36080 error You can get information on how to open an issue for this project with:
36080 error     npm bugs Dillinger
36080 error Or if that isn't available, you can get their info via:
36080 error     npm owner ls Dillinger
36080 error There is likely additional logging output above.
36081 verbose exit [ 1, true ]
```

**Comment by benjamin-albert** [comment]
@wirehack7 Is this issue still relevant?

Assuming it is still relevant you can [download a pre-built version](https://github.com/benjamin-albert/dillinger/releases) of Dillinger from my fork.

This allows you to **skip** running the build:

    gulp build --prod

After you download a pre-build version you can run:

    npm install --production

Which only installs dependencies (it skips devDependencies like gulp).

**Comment by wirehack7** [comment]
I am still getting an error:

```
17:40:55 Sun Jul 17 dillinger@[censored].pw [~] $: unzip pre-built.zip
Archive:  pre-built.zip
  inflating: Dockerfile
  inflating: LICENSE
  inflating: Procfile
  inflating: README.md
  inflating: app.js
  inflating: config.js
  inflating: deploy.yml
  inflating: dillinger.service
  inflating: docker-compose.yml
   creating: gulp/
  inflating: gulpfile.js
  inflating: karma.conf.js
   creating: nginx/
   creating: node_modules/
  inflating: npm-shrinkwrap.json
  inflating: nsolid.yml
  inflating: package.json
   creating: plugins/
   creating: public/
   creating: routes/
   creating: views/
  inflating: webpack.config.js
  inflating: nginx/dillinger.conf
   creating: plugins/core/
   creating: plugins/dropbox/
   creating: plugins/github/
   creating: plugins/googledrive/
   creating: plugins/onedrive/
  inflating: public/apple-touch-icon.png
   creating: public/css/
  inflating: public/favicon.ico
   creating: public/files/
   creating: public/img/
   creating: public/js/
  inflating: public/robots.txt
   creating: public/scss/
  inflating: routes/index.js
   creating: views/dropdowns/
  inflating: views/editor-headers.ejs
  inflating: views/editor.ejs
  inflating: views/footer.ejs
   creating: views/icons/
  inflating: views/index.ejs
  inflating: views/navbar.ejs
  inflating: views/notification.ejs
  inflating: views/overlay.ejs
  inflating: views/preview.ejs
  inflating: views/sidebar.ejs
  inflating: views/splashscreen.ejs
  inflating: views/title.ejs
  inflating: views/zen-mode.ejs
  inflating: plugins/core/markdown-it.js
  inflating: plugins/core/server.js
  inflating: plugins/dropbox/README.md
  inflating: plugins/dropbox/client.js
  inflating: plugins/dropbox/dropbox.js
  inflating: plugins/dropbox/parallel.js
  inflating: plugins/dropbox/server.js
  inflating: plugins/github/README.md
  inflating: plugins/github/client.js
  inflating: plugins/github/github.js
  inflating: plugins/github/server.js
  inflating: plugins/googledrive/README.md
  inflating: plugins/googledrive/client.js
  inflating: plugins/googledrive/googledrive.js
  inflating: plugins/googledrive/server.js
  inflating: plugins/onedrive/README.md
  inflating: plugins/onedrive/client.js
  inflating: plugins/onedrive/onedrive.js
  inflating: plugins/onedrive/server.js
  inflating: public/css/app.css
   creating: public/files/html/
   creating: public/files/md/
  inflating: public/img/avatar_d_128x128.png
  inflating: public/img/avatar_d_16x16.png
  inflating: public/img/avatar_d_256x256.png
  inflating: public/img/avatar_d_64x64.png
   creating: public/img/icons/
  inflating: public/js/app.js
   creating: public/js/base/
  inflating: public/js/bundle.js
   creating: public/js/components/
   creating: public/js/documents/
   creating: public/js/factorys/
   creating: public/js/file-import/
   creating: public/js/plugins/
   creating: public/js/services/
   creating: public/js/user/
   creating: public/js/zen-mode/
  inflating: views/dropdowns/documents.ejs
  inflating: views/dropdowns/export_as.ejs
  inflating: views/dropdowns/import_from.ejs
  inflating: views/dropdowns/link_unlink.ejs
  inflating: views/dropdowns/save_to.ejs
  inflating: views/dropdowns/settings.ejs
  inflating: views/icons/branding.ejs
  inflating: views/icons/linked.ejs
  inflating: views/icons/preview.ejs
  inflating: views/icons/settings.ejs
  inflating: public/img/icons/dillinger-big.svg
  inflating: public/img/icons/dillinger.svg
  inflating: public/img/icons/enter-zen.png
  inflating: public/img/icons/enter-zen.svg
  inflating: public/img/icons/exit-zen.svg
  inflating: public/img/icons/file.svg
  inflating: public/img/icons/linked.svg
  inflating: public/img/icons/megaphone.svg
  inflating: public/img/icons/octocat.svg
  inflating: public/img/icons/preview.svg
  inflating: public/img/icons/settings.svg
  inflating: public/js/base/base.controller.js
  inflating: public/js/base/diNotify.html
  inflating: public/js/components/document-title.directive.html
  inflating: public/js/components/document-title.directive.js
  inflating: public/js/components/focus.factory.js
  inflating: public/js/components/preview.directive.js
  inflating: public/js/components/switch.directive.html
  inflating: public/js/components/switch.directive.js
  inflating: public/js/components/toggle-menu.directive.html
  inflating: public/js/components/toggle-menu.directive.js
  inflating: public/js/components/toggle-preview.directive.js
  inflating: public/js/components/toggle-settings.directive.js
  inflating: public/js/components/wtfisdillinger-modal.controller.js
  inflating: public/js/components/wtfisdillinger-modal.directive.html
  inflating: public/js/documents/delete-modal.controller.js
  inflating: public/js/documents/delete-modal.directive.html
  inflating: public/js/documents/documents-export.controller.js
  inflating: public/js/documents/documents.controller.js
  inflating: public/js/documents/theme-dillinger.js
  inflating: public/js/factorys/sheet.factory.js
  inflating: public/js/file-import/choose-file.directive.js
  inflating: public/js/file-import/drop-target.directive.js
  inflating: public/js/file-import/import-file.controller.js
   creating: public/js/plugins/dropbox/
   creating: public/js/plugins/github/
   creating: public/js/plugins/google-drive/
   creating: public/js/plugins/one-drive/
  inflating: public/js/services/debounce.service.js
  inflating: public/js/services/documents.service.js
  inflating: public/js/services/notification.service.js
  inflating: public/js/services/user.service.js
  inflating: public/js/services/wordscount.service.js
  inflating: public/js/user/user.controller.js
  inflating: public/js/zen-mode/zen-mode-toggle.directive.html
  inflating: public/js/zen-mode/zen-mode-toggle.directive.js
  inflating: public/js/zen-mode/zen-mode.controller.js
  inflating: public/js/zen-mode/zen-mode.directive.html
  inflating: public/js/plugins/dropbox/dropbox-modal.controller.js
  inflating: public/js/plugins/dropbox/dropbox-modal.directive.html
  inflating: public/js/plugins/dropbox/dropbox.controller.js
  inflating: public/js/plugins/dropbox/dropbox.controller.spec.js
  inflating: public/js/plugins/dropbox/dropbox.service.js
  inflating: public/js/plugins/dropbox/dropbox.service.spec.js
  inflating: public/js/plugins/github/github-modal.controller.js
  inflating: public/js/plugins/github/github-modal.directive.html
  inflating: public/js/plugins/github/github-modal.scope.html
  inflating: public/js/plugins/github/github.controller.js
  inflating: public/js/plugins/github/github.controller.spec.js
  inflating: public/js/plugins/github/github.service.js
  inflating: public/js/plugins/github/github.service.spec.js
  inflating: public/js/plugins/google-drive/google-drive-modal.controller.js
  inflating: public/js/plugins/google-drive/google-drive-modal.directive.html
  inflating: public/js/plugins/google-drive/google-drive.controller.js
  inflating: public/js/plugins/google-drive/google-drive.controller.spec.js
  inflating: public/js/plugins/google-drive/google-drive.service.js
  inflating: public/js/plugins/google-drive/google-drive.service.spec.js
  inflating: public/js/plugins/one-drive/one-drive-modal.controller.js
  inflating: public/js/plugins/one-drive/one-drive-modal.directive.html
  inflating: public/js/plugins/one-drive/one-drive.controller.js
  inflating: public/js/plugins/one-drive/one-drive.controller.spec.js
  inflating: public/js/plugins/one-drive/one-drive.service.js
  inflating: public/js/plugins/one-drive/one-drive.service.spec.js
17:41:00 Sun Jul 17 dillinger@[censored].pw [~] $: ls
app.js      dillinger.service   gulp           LICENSE       npm-shrinkwrap.json  plugins        public     views
config.js   docker-compose.yml  gulpfile.js    nginx         nsolid.yml           pre-built.zip  README.md  webpack.config.js
deploy.yml  Dockerfile          karma.conf.js  node_modules  package.json         Procfile       routes
17:41:02 Sun Jul 17 dillinger@[censored].pw [~] $: ls
app.js      dillinger.service   gulp           LICENSE       npm-shrinkwrap.json  plugins        public     views
config.js   docker-compose.yml  gulpfile.js    nginx         nsolid.yml           pre-built.zip  README.md  webpack.config.js
deploy.yml  Dockerfile          karma.conf.js  node_modules  package.json         Procfile       routes
17:41:04 Sun Jul 17 dillinger@[censored].pw [~] $: npm install --production
npm WARN prefer global marked@0.3.5 should be installed with -g
markdown-it-mark@1.0.0 node_modules/markdown-it-mark

markdown-it-abbr@1.0.3 node_modules/markdown-it-abbr

markdown-it-footnote@1.0.0 node_modules/markdown-it-footnote

markdown-it-ins@1.0.0 node_modules/markdown-it-ins

markdown-it-sub@1.0.0 node_modules/markdown-it-sub

markdown-it-deflist@1.0.0 node_modules/markdown-it-deflist

markdown-it-sup@1.0.0 node_modules/markdown-it-sup

markdown-it-toc@1.1.0 node_modules/markdown-it-toc

keymaster@1.6.2 node_modules/keymaster

depd@1.1.0 node_modules/depd

angular-bootstrap@0.12.2 node_modules/angular-bootstrap

marked@0.3.5 node_modules/marked

colors@1.1.2 node_modules/colors

es6-promise@3.1.2 node_modules/es6-promise

katex@0.2.0 node_modules/katex

method-override@2.3.5 node_modules/method-override
├── vary@1.0.1
├── methods@1.1.2
└── parseurl@1.3.1

cookie-parser@1.4.1 node_modules/cookie-parser
├── cookie-signature@1.0.6
└── cookie@0.2.3

serve-favicon@2.3.0 node_modules/serve-favicon
├── etag@1.7.0
├── parseurl@1.3.1
├── fresh@0.3.0
└── ms@0.7.1

debug@2.2.0 node_modules/debug
└── ms@0.7.1

angular@1.5.0 node_modules/angular

markdown-it-checkbox@1.1.0 node_modules/markdown-it-checkbox
└── underscore@1.8.3

morgan@1.7.0 node_modules/morgan
├── on-headers@1.0.1
├── basic-auth@1.0.3
└── on-finished@2.3.0 (ee-first@1.1.1)

cookie-session@1.2.0 node_modules/cookie-session
├── on-headers@1.0.1
└── cookies@0.5.0 (keygrip@1.0.1)

ejs@2.4.1 node_modules/ejs

connect@3.4.1 node_modules/connect
├── utils-merge@1.0.0
├── parseurl@1.3.1
└── finalhandler@0.4.1 (escape-html@1.0.3, unpipe@1.0.0, on-finished@2.3.0)

serve-static@1.10.2 node_modules/serve-static
├── escape-html@1.0.3
├── parseurl@1.3.1
└── send@0.13.1 (destroy@1.0.4, fresh@0.3.0, etag@1.7.0, range-parser@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, on-finished@2.3.0, http-errors@1.3.1)

compression@1.6.1 node_modules/compression
├── on-headers@1.0.1
├── vary@1.1.0
├── bytes@2.2.0
├── compressible@2.0.7 (mime-db@1.22.0)
└── accepts@1.3.1 (negotiator@0.6.0, mime-types@2.1.10)

errorhandler@1.4.3 node_modules/errorhandler
├── escape-html@1.0.3
└── accepts@1.3.1 (negotiator@0.6.0, mime-types@2.1.10)

body-parser@1.15.0 node_modules/body-parser
├── content-type@1.0.1
├── bytes@2.2.0
├── raw-body@2.1.5 (unpipe@1.0.0)
├── qs@6.1.0
├── http-errors@1.4.0 (statuses@1.2.1, inherits@2.0.1)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── iconv-lite@0.4.13
└── type-is@1.6.11 (media-typer@0.3.0, mime-types@2.1.10)

express@4.13.4 node_modules/express
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── cookie-signature@1.0.6
├── utils-merge@1.0.0
├── content-type@1.0.1
├── vary@1.0.1
├── methods@1.1.2
├── merge-descriptors@1.0.1
├── cookie@0.1.5
├── fresh@0.3.0
├── etag@1.7.0
├── path-to-regexp@0.1.7
├── range-parser@1.0.3
├── content-disposition@0.5.1
├── parseurl@1.3.1
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.1 (unpipe@1.0.0)
├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
├── type-is@1.6.11 (media-typer@0.3.0, mime-types@2.1.10)
├── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.10)
└── send@0.13.1 (destroy@1.0.4, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)

rc@0.3.0 node_modules/rc
├── deep-extend@0.2.11
├── ini@1.1.0
└── optimist@0.3.7 (wordwrap@0.0.3)

dbox@0.6.4 node_modules/dbox
└── request@2.9.153

jquery@2.2.1 node_modules/jquery

markdown-it@4.4.0 node_modules/markdown-it
├── linkify-it@1.2.0
├── mdurl@1.0.1
├── uc.micro@1.0.0
├── entities@1.1.1
└── argparse@1.0.6 (sprintf-js@1.0.3)

highlight.js@8.9.1 node_modules/highlight.js

request@2.69.0 node_modules/request
├── aws-sign2@0.6.0
├── forever-agent@0.6.1
├── tunnel-agent@0.4.2
├── oauth-sign@0.8.1
├── is-typedarray@1.0.0
├── caseless@0.11.0
├── stringstream@0.0.5
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── tough-cookie@2.2.1
├── node-uuid@1.4.7
├── qs@6.0.2
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── mime-types@2.1.10 (mime-db@1.22.0)
├── form-data@1.0.0-rc3 (async@1.5.2)
├── aws4@1.2.1 (lru-cache@2.7.3)
├── hawk@3.1.3 (cryptiles@2.0.5, boom@2.10.1, sntp@1.0.9, hoek@2.16.3)
├── bl@1.0.3 (readable-stream@2.0.5)
├── http-signature@1.1.1 (assert-plus@0.2.0, jsprim@1.2.2, sshpk@1.7.4)
└── har-validator@2.0.6 (pinkie-promise@2.0.0, commander@2.9.0, chalk@1.1.1, is-my-json-valid@2.13.1)

brace@0.4.1 node_modules/brace
└── w3c-blob@0.0.1

googleapis@2.1.7 node_modules/googleapis
├── string-template@0.2.1
├── async@1.5.2
├── gapitoken@0.1.5 (jws@3.0.0)
├── request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oauth-sign@0.8.1, form-data@1.0.0-rc3, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.1, node-uuid@1.4.7, qs@5.2.0, combined-stream@1.0.5, mime-types@2.1.10, http-signature@0.11.0, hawk@3.1.3, bl@1.0.3, har-validator@2.0.6)
└── google-auth-library@0.9.7 (lodash.noop@3.0.1, async@1.4.2, jws@3.0.0, request@2.60.0, gtoken@1.2.0)

markdown-it-math@3.0.2 node_modules/markdown-it-math
└── ascii2mathml@0.5.3 (minimist@1.2.0, babel@5.8.35)
17:41:56 Sun Jul 17 dillinger@[censored].pw [~] $: ls
app.js      dillinger.service   gulp           LICENSE       npm-shrinkwrap.json  plugins        public     views
config.js   docker-compose.yml  gulpfile.js    nginx         nsolid.yml           pre-built.zip  README.md  webpack.config.js
deploy.yml  Dockerfile          karma.conf.js  node_modules  package.json         Procfile       routes
17:42:01 Sun Jul 17 dillinger@[censored].pw [~] $: npm start

> Dillinger@3.3.0 start /home/dillinger
> node app.js

Dropbox config not found at /home/dillinger/plugins/dropbox/dropbox-config.json. Plugin disabled.
Github config not found at /home/dillinger/plugins/github/github-config.json. Plugin disabled.
Google Drive config not found at /home/dillinger/plugins/googledrive/googledrive-config.json. Plugin disabled.
OneDrive config not found at /home/dillinger/plugins/onedrive/onedrive-config.json. Plugin disabled.
module.js:327
    throw err;
    ^

Error: Cannot find module 'temp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/dillinger/plugins/core/server.js:6:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! Dillinger@3.3.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Dillinger@3.3.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the Dillinger package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Dillinger
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls Dillinger
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dillinger/npm-debug.log
17:42:05 Sun Jul 17 dillinger@[censored].pw [~] $:
```

**Comment by joemccann** [comment]
Try a fresh install from source...

`npm clean cache`

then

`npm i -d`

then

`npm predeploy`

then

`npm start`

Let me what happens next
