### ISSUE TITLE
401 - Bad credentials when deploying to GitHub releases

### ISSUE THREAD

**Issue by benjamin-albert** [joemccann/dillinger#557]
I created the 3.5.1 release which triggers a travis CI build which deploys the pre-built try/zip files to GitHub releases.

When it gets to the deploy step it fails because of bad credentials:

```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/connection.rb:19:in `get'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/client/users.rb:34:in `user'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/provider/releases.rb:43:in `user'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/provider/releases.rb:68:in `setup_auth'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/provider/releases.rb:72:in `check_auth'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/provider.rb:131:in `block in deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/cli.rb:41:in `fold'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/provider.rb:130:in `deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/cli.rb:32:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/cli.rb:7:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/bin/dpl:5:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

@joemccann Can you please follow the instructions for [setting up your own API key](https://docs.travis-ci.com/user/deployment/releases).

I a few words you [install the Travis CI Client](https://github.com/travis-ci/travis.rb#installation) and run:

```
travis setup releases
```

**Comment by joemccann** [comment]
I don't know anyone downloading the tarball tbh. With source available and docker images, this seems like a waste of time, no? If you want, I can send you the API key and you can set it up, but seems like no one is using this
