### ISSUE TITLE
Preview Not Working

### ISSUE THREAD

**Issue by LadyDeathKZN** [joemccann/dillinger#733]
Hi, any form of a preview is not working, I have updated the gulp-sass to 3.0.0 which was causing other issues with the gitclone. I am getting this error then the node app just exits, when trying to preview anything. Have linked my dropbox and that all is fine none the less.
```
fs.js:134
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:134:11)
    at Object.unlink (fs.js:949:14)
    at G:\apps\dillinger\plugins\core\server.js:147:12
    at G:\apps\dillinger\node_modules\express\lib\response.js:434:22
    at SendStream.onend (G:\apps\dillinger\node_modules\express\lib\response.js:1051:5)
    at SendStream.emit (events.js:200:13)
    at ReadStream.onend (G:\apps\dillinger\node_modules\send\index.js:821:10)
    at ReadStream.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1137:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by joemccann** [comment]
Hmm I'd need to know a lot more about your setup to help you out.

If you do a fresh install, what happens?

**Comment by LadyDeathKZN** [comment]
Hi, this is a new install, or clone. Have updated all the plugins. Any suggestions?

**Comment by jloneva** [comment]
Having the same exact issue when trying to preview as PDF. Running `node app` locally on Windows 10 OS.

**Comment by joemccann** [comment]
duplicate (PDF not working is a known issue)
